### ISSUE TITLE
Create requirements.md.

### ISSUE THREAD

**Issue by eugenemonnier** [memlly/mem-or-y#2]
Using the [Software Requirements Document](https://codefellows.github.io/common_curriculum/projects/SoftwareReqs), create a new file within your main GH repo named requirements.md. Include in this doc the required information for your software reqs for your project as a whole.

**Comment by eugenemonnier** [comment]
Divide into 3 main parts of Software Requirements Document
1. **Vision** 
2. **Scope (In/Out)**
3. **Functional Requirements**

**Comment by ghost** [comment]
requirements.md is complete.
Closing issue.
