### ISSUE TITLE
Create wireframe for index.html

### ISSUE THREAD

**Issue by eugenemonnier** [memlly/mem-or-y#3]
As a user, when I am on the “Home” page, I would want to see a page that has a visually appealing page layout.

**Feature Tasks**
- Main page has a basic stylized header
- Main page has a basic stylized body
- Main page has a basic stylized footer

**Acceptance Tests**
- [x] All aspects of whiteboarded  Main wireframe show correctly when page loads.

**Comment by eugenemonnier** [comment]
![Main](https://user-images.githubusercontent.com/16282245/71527705-6a7a7280-2891-11ea-8c5e-65048c50aa3a.jpg)

**Comment by ghost** [comment]
Should be good now. Only two things are missing (aside from the game itself) on this issue now:
The user score, and difficulty displays are not present on the user bar. The login form exists, and when submitted, hides the info section, and displays the game section.

Will push and submit PR on this issue.
