### ISSUE TITLE
Add Login with localStorage

### ISSUE THREAD

**Issue by eugenemonnier** [memlly/mem-or-y#31]
As a user, I want to be able to log in and out of the web app and have it remember my username and game data.

**Feature Tasks**
- Login form accepts and stores user input.
- Login form cannot be empty or blank.
- Include capability for user to log out of web app.
- All user log in/out data is stored in localStorage and kept up to date.

**Acceptance Tests**
- [x] User is prompted if username value is set to empty string.
- [x] User `loggedIn` value is set to `true` upon log in.
- [x] User name is displayed after successful log in.
- [x] User `loggedIn` value is set to `false` upon log out.
- [x] User data and `loggedIn` data is set to localStorage.
- [x] Web app verifies if user is logged in upon page load.
- [x] If user already exists in localStorage, when user re-logs in, no new user data is created and that user is logged in

**Comment by ghost** [comment]
User login / logout data in localStorage should be resolved now.
