### ISSUE TITLE
Bug: User can have infinite score without playing

### ISSUE THREAD

**Issue by eugenemonnier** [memlly/mem-or-y#78]
When I create a new user then click over to the stats page, that user's score shows as infinite.

**Expected Results**
When a new user creates an account and goes to the stats page without completing one session of the game. Their highscore shows as 0.

**Actual Results**
When a new user creates an account and goes to the stats page without completing one session of the game. Their highscore shows as "Infinite".

**Comment by ghost** [comment]
Resolved.
